---
id: rurema-2024-10
base_name: rurema-2024-10
tags:
- ruby
presentation_date: '2024-10-05'
presentation_start_time:
presentation_end_time:
version: 2024.10.5.0
licenses: []
slideshare_id: ruby-ruby-11-2024-10-05
speaker_deck_id: rubynori-ben-yu-rihuarensumaniyuarunoxian-zai-towei-lai
vimeo_id:
youtube_id:
width: 1920
height: 1200
source_code_uri:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
